# config_transformers.yml
language: pt

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "bert-base-multilingual-cased"
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

policies:
  - name: RulePolicy
